/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_windowMain (void)
{
  GtkWidget *windowMain;
  GtkWidget *vboxMain;
  GtkWidget *label14;
  GtkWidget *notebook1;
  GtkWidget *toolbar2;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *tmp_image;
  GtkWidget *buttonUpdate;
  GtkWidget *buttonQuit2;
  GtkWidget *label15;
  GtkWidget *vbox3;
  GtkWidget *toolbar1;
  GtkWidget *buttonRefresh;
  GtkWidget *buttonSync;
  GtkWidget *buttonSetup;
  GtkWidget *buttonQuit;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeChanges;
  GtkWidget *hbuttonbox1;
  GtkWidget *buttonAllRemote;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label8;
  GtkWidget *buttonRemote;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label9;
  GtkWidget *buttonSkip;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label10;
  GtkWidget *buttonLocal;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label11;
  GtkWidget *buttonAllLocal;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label12;
  GtkWidget *label16;
  GtkWidget *statusbar;

  windowMain = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (windowMain, "windowMain");
  gtk_window_set_title (GTK_WINDOW (windowMain), _("MtpSync"));
  gtk_window_set_position (GTK_WINDOW (windowMain), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (windowMain), 200, 200);

  vboxMain = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vboxMain, "vboxMain");
  gtk_widget_show (vboxMain);
  gtk_container_add (GTK_CONTAINER (windowMain), vboxMain);

  label14 = gtk_label_new (_("What do you want to do?"));
  gtk_widget_set_name (label14, "label14");
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (vboxMain), label14, FALSE, FALSE, 0);

  notebook1 = gtk_notebook_new ();
  gtk_widget_set_name (notebook1, "notebook1");
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (vboxMain), notebook1, TRUE, TRUE, 0);
  gtk_notebook_set_tab_pos (GTK_NOTEBOOK (notebook1), GTK_POS_BOTTOM);

  toolbar2 = gtk_toolbar_new ();
  gtk_widget_set_name (toolbar2, "toolbar2");
  gtk_widget_show (toolbar2);
  gtk_container_add (GTK_CONTAINER (notebook1), toolbar2);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar2), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar2));

  tmp_image = gtk_image_new_from_stock ("gtk-media-play", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  buttonUpdate = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Setup"));
  gtk_widget_set_name (buttonUpdate, "buttonUpdate");
  gtk_widget_show (buttonUpdate);
  gtk_tool_item_set_expand (GTK_TOOL_ITEM (buttonUpdate), TRUE);
  gtk_container_add (GTK_CONTAINER (toolbar2), buttonUpdate);
  gtk_tool_item_set_is_important (GTK_TOOL_ITEM (buttonUpdate), TRUE);

  buttonQuit2 = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-quit");
  gtk_widget_set_name (buttonQuit2, "buttonQuit2");
  gtk_widget_show (buttonQuit2);
  gtk_tool_item_set_expand (GTK_TOOL_ITEM (buttonQuit2), TRUE);
  gtk_container_add (GTK_CONTAINER (toolbar2), buttonQuit2);
  gtk_tool_item_set_is_important (GTK_TOOL_ITEM (buttonQuit2), TRUE);

  label15 = gtk_label_new (_("Simple"));
  gtk_widget_set_name (label15, "label15");
  gtk_widget_show (label15);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label15);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox3, "vbox3");
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox3);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_set_name (toolbar1, "toolbar1");
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (vbox3), toolbar1, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_BOTH);
  gtk_toolbar_set_show_arrow (GTK_TOOLBAR (toolbar1), FALSE);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1));

  tmp_image = gtk_image_new_from_stock ("gtk-refresh", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  buttonRefresh = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Refresh"));
  gtk_widget_set_name (buttonRefresh, "buttonRefresh");
  gtk_widget_show (buttonRefresh);
  gtk_tool_item_set_expand (GTK_TOOL_ITEM (buttonRefresh), TRUE);
  gtk_container_add (GTK_CONTAINER (toolbar1), buttonRefresh);

  tmp_image = gtk_image_new_from_stock ("gtk-media-play", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  buttonSync = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Begin Sync"));
  gtk_widget_set_name (buttonSync, "buttonSync");
  gtk_widget_show (buttonSync);
  gtk_tool_item_set_expand (GTK_TOOL_ITEM (buttonSync), TRUE);
  gtk_container_add (GTK_CONTAINER (toolbar1), buttonSync);
  gtk_tool_item_set_is_important (GTK_TOOL_ITEM (buttonSync), TRUE);

  tmp_image = gtk_image_new_from_stock ("gtk-properties", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  buttonSetup = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Setup"));
  gtk_widget_set_name (buttonSetup, "buttonSetup");
  gtk_widget_show (buttonSetup);
  gtk_tool_item_set_expand (GTK_TOOL_ITEM (buttonSetup), TRUE);
  gtk_container_add (GTK_CONTAINER (toolbar1), buttonSetup);
  gtk_tool_item_set_is_important (GTK_TOOL_ITEM (buttonSetup), TRUE);

  buttonQuit = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-quit");
  gtk_widget_set_name (buttonQuit, "buttonQuit");
  gtk_widget_show (buttonQuit);
  gtk_tool_item_set_expand (GTK_TOOL_ITEM (buttonQuit), TRUE);
  gtk_container_add (GTK_CONTAINER (toolbar1), buttonQuit);
  gtk_tool_item_set_is_important (GTK_TOOL_ITEM (buttonQuit), TRUE);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow1, "scrolledwindow1");
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox3), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_SHADOW_IN);

  treeChanges = gtk_tree_view_new ();
  gtk_widget_set_name (treeChanges, "treeChanges");
  gtk_widget_show (treeChanges);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeChanges);
  gtk_widget_set_sensitive (treeChanges, FALSE);
  gtk_tree_view_set_enable_search (GTK_TREE_VIEW (treeChanges), FALSE);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox1, "hbuttonbox1");
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox3), hbuttonbox1, FALSE, TRUE, 0);

  buttonAllRemote = gtk_button_new ();
  gtk_widget_set_name (buttonAllRemote, "buttonAllRemote");
  gtk_widget_show (buttonAllRemote);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), buttonAllRemote);
  GTK_WIDGET_SET_FLAGS (buttonAllRemote, GTK_CAN_DEFAULT);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment1, "alignment1");
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttonAllRemote), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox1, "hbox1");
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-goto-first", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image1, "image1");
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("All from Remote"));
  gtk_widget_set_name (label8, "label8");
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox1), label8, FALSE, FALSE, 0);

  buttonRemote = gtk_button_new ();
  gtk_widget_set_name (buttonRemote, "buttonRemote");
  gtk_widget_show (buttonRemote);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), buttonRemote);
  GTK_WIDGET_SET_FLAGS (buttonRemote, GTK_CAN_DEFAULT);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment2, "alignment2");
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttonRemote), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox2, "hbox2");
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image2, "image2");
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("From Remote"));
  gtk_widget_set_name (label9, "label9");
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox2), label9, FALSE, FALSE, 0);

  buttonSkip = gtk_button_new ();
  gtk_widget_set_name (buttonSkip, "buttonSkip");
  gtk_widget_show (buttonSkip);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), buttonSkip);
  GTK_WIDGET_SET_FLAGS (buttonSkip, GTK_CAN_DEFAULT);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment3, "alignment3");
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (buttonSkip), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox3, "hbox3");
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-dialog-question", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image3, "image3");
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Skip"));
  gtk_widget_set_name (label10, "label10");
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox3), label10, FALSE, FALSE, 0);

  buttonLocal = gtk_button_new ();
  gtk_widget_set_name (buttonLocal, "buttonLocal");
  gtk_widget_show (buttonLocal);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), buttonLocal);
  GTK_WIDGET_SET_FLAGS (buttonLocal, GTK_CAN_DEFAULT);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment4, "alignment4");
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (buttonLocal), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox4, "hbox4");
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image4, "image4");
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("From Local"));
  gtk_widget_set_name (label11, "label11");
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox4), label11, FALSE, FALSE, 0);

  buttonAllLocal = gtk_button_new ();
  gtk_widget_set_name (buttonAllLocal, "buttonAllLocal");
  gtk_widget_show (buttonAllLocal);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), buttonAllLocal);
  GTK_WIDGET_SET_FLAGS (buttonAllLocal, GTK_CAN_DEFAULT);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment5, "alignment5");
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (buttonAllLocal), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox5, "hbox5");
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-goto-last", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image5, "image5");
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("All from Local"));
  gtk_widget_set_name (label12, "label12");
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox5), label12, FALSE, FALSE, 0);

  label16 = gtk_label_new (_("Advanced"));
  gtk_widget_set_name (label16, "label16");
  gtk_widget_show (label16);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label16);

  statusbar = gtk_statusbar_new ();
  gtk_widget_set_name (statusbar, "statusbar");
  gtk_widget_show (statusbar);
  gtk_box_pack_start (GTK_BOX (vboxMain), statusbar, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonUpdate, "clicked",
                    G_CALLBACK (on_buttonUpdate_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonQuit2, "clicked",
                    G_CALLBACK (on_buttonQuit_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonRefresh, "clicked",
                    G_CALLBACK (on_buttonRefresh_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSync, "clicked",
                    G_CALLBACK (on_buttonSync_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSetup, "clicked",
                    G_CALLBACK (on_buttonSetup_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonQuit, "clicked",
                    G_CALLBACK (on_buttonQuit_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAllRemote, "clicked",
                    G_CALLBACK (on_buttonAllRemote_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonRemote, "clicked",
                    G_CALLBACK (on_buttonRemote_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSkip, "clicked",
                    G_CALLBACK (on_buttonSkip_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonLocal, "clicked",
                    G_CALLBACK (on_buttonLocal_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAllLocal, "clicked",
                    G_CALLBACK (on_buttonAllLocal_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowMain, windowMain, "windowMain");
  GLADE_HOOKUP_OBJECT (windowMain, vboxMain, "vboxMain");
  GLADE_HOOKUP_OBJECT (windowMain, label14, "label14");
  GLADE_HOOKUP_OBJECT (windowMain, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (windowMain, toolbar2, "toolbar2");
  GLADE_HOOKUP_OBJECT (windowMain, buttonUpdate, "buttonUpdate");
  GLADE_HOOKUP_OBJECT (windowMain, buttonQuit2, "buttonQuit2");
  GLADE_HOOKUP_OBJECT (windowMain, label15, "label15");
  GLADE_HOOKUP_OBJECT (windowMain, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (windowMain, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (windowMain, buttonRefresh, "buttonRefresh");
  GLADE_HOOKUP_OBJECT (windowMain, buttonSync, "buttonSync");
  GLADE_HOOKUP_OBJECT (windowMain, buttonSetup, "buttonSetup");
  GLADE_HOOKUP_OBJECT (windowMain, buttonQuit, "buttonQuit");
  GLADE_HOOKUP_OBJECT (windowMain, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (windowMain, treeChanges, "treeChanges");
  GLADE_HOOKUP_OBJECT (windowMain, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (windowMain, buttonAllRemote, "buttonAllRemote");
  GLADE_HOOKUP_OBJECT (windowMain, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (windowMain, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (windowMain, image1, "image1");
  GLADE_HOOKUP_OBJECT (windowMain, label8, "label8");
  GLADE_HOOKUP_OBJECT (windowMain, buttonRemote, "buttonRemote");
  GLADE_HOOKUP_OBJECT (windowMain, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (windowMain, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (windowMain, image2, "image2");
  GLADE_HOOKUP_OBJECT (windowMain, label9, "label9");
  GLADE_HOOKUP_OBJECT (windowMain, buttonSkip, "buttonSkip");
  GLADE_HOOKUP_OBJECT (windowMain, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (windowMain, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (windowMain, image3, "image3");
  GLADE_HOOKUP_OBJECT (windowMain, label10, "label10");
  GLADE_HOOKUP_OBJECT (windowMain, buttonLocal, "buttonLocal");
  GLADE_HOOKUP_OBJECT (windowMain, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (windowMain, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (windowMain, image4, "image4");
  GLADE_HOOKUP_OBJECT (windowMain, label11, "label11");
  GLADE_HOOKUP_OBJECT (windowMain, buttonAllLocal, "buttonAllLocal");
  GLADE_HOOKUP_OBJECT (windowMain, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (windowMain, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (windowMain, image5, "image5");
  GLADE_HOOKUP_OBJECT (windowMain, label12, "label12");
  GLADE_HOOKUP_OBJECT (windowMain, label16, "label16");
  GLADE_HOOKUP_OBJECT (windowMain, statusbar, "statusbar");

  return windowMain;
}

GtkWidget*
create_dialogSetup (void)
{
  GtkWidget *dialogSetup;
  GtkWidget *dialog_vbox1;
  GtkWidget *vbox2;
  GtkWidget *label7;
  GtkWidget *table1;
  GtkWidget *fileMusic;
  GtkWidget *filePlaylists;
  GtkWidget *fileImages;
  GtkWidget *fileVideo;
  GtkWidget *fileZencast;
  GtkWidget *fileOrganizer;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *label3;
  GtkWidget *checkMusic;
  GtkWidget *checkPlaylists;
  GtkWidget *checkImages;
  GtkWidget *checkVideos;
  GtkWidget *checkZencasts;
  GtkWidget *checkOrganizer;
  GtkWidget *dialog_action_area1;
  GtkWidget *cancelbutton1;
  GtkWidget *okbutton1;

  dialogSetup = gtk_dialog_new ();
  gtk_widget_set_name (dialogSetup, "dialogSetup");
  gtk_window_set_title (GTK_WINDOW (dialogSetup), _("Properties"));
  gtk_window_set_position (GTK_WINDOW (dialogSetup), GTK_WIN_POS_CENTER_ON_PARENT);
  gtk_window_set_modal (GTK_WINDOW (dialogSetup), TRUE);
  gtk_window_set_type_hint (GTK_WINDOW (dialogSetup), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (dialogSetup)->vbox;
  gtk_widget_set_name (dialog_vbox1, "dialog_vbox1");
  gtk_widget_show (dialog_vbox1);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox2, "vbox2");
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), vbox2, TRUE, TRUE, 0);

  label7 = gtk_label_new (_("Select paths to syncronise"));
  gtk_widget_set_name (label7, "label7");
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (vbox2), label7, FALSE, FALSE, 0);

  table1 = gtk_table_new (6, 3, FALSE);
  gtk_widget_set_name (table1, "table1");
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox2), table1, TRUE, TRUE, 0);

  fileMusic = gtk_file_chooser_button_new (_("Select A Folder"), GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER);
  gtk_widget_set_name (fileMusic, "fileMusic");
  gtk_widget_show (fileMusic);
  gtk_table_attach (GTK_TABLE (table1), fileMusic, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  filePlaylists = gtk_file_chooser_button_new (_("Select A Folder"), GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER);
  gtk_widget_set_name (filePlaylists, "filePlaylists");
  gtk_widget_show (filePlaylists);
  gtk_table_attach (GTK_TABLE (table1), filePlaylists, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  fileImages = gtk_file_chooser_button_new (_("Select A Folder"), GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER);
  gtk_widget_set_name (fileImages, "fileImages");
  gtk_widget_show (fileImages);
  gtk_table_attach (GTK_TABLE (table1), fileImages, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  fileVideo = gtk_file_chooser_button_new (_("Select A Folder"), GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER);
  gtk_widget_set_name (fileVideo, "fileVideo");
  gtk_widget_show (fileVideo);
  gtk_table_attach (GTK_TABLE (table1), fileVideo, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  fileZencast = gtk_file_chooser_button_new (_("Select A Folder"), GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER);
  gtk_widget_set_name (fileZencast, "fileZencast");
  gtk_widget_show (fileZencast);
  gtk_table_attach (GTK_TABLE (table1), fileZencast, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  fileOrganizer = gtk_file_chooser_button_new (_("Select A Folder"), GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER);
  gtk_widget_set_name (fileOrganizer, "fileOrganizer");
  gtk_widget_show (fileOrganizer);
  gtk_table_attach (GTK_TABLE (table1), fileOrganizer, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  label1 = gtk_label_new (_("Music"));
  gtk_widget_set_name (label1, "label1");
  gtk_widget_show (label1);
  gtk_table_attach (GTK_TABLE (table1), label1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label1), 0, 0.5);

  label2 = gtk_label_new (_("Playlists"));
  gtk_widget_set_name (label2, "label2");
  gtk_widget_show (label2);
  gtk_table_attach (GTK_TABLE (table1), label2, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label2), 0, 0.5);

  label4 = gtk_label_new (_("Videos"));
  gtk_widget_set_name (label4, "label4");
  gtk_widget_show (label4);
  gtk_table_attach (GTK_TABLE (table1), label4, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label4), 0, 0.5);

  label5 = gtk_label_new (_("Zencasts"));
  gtk_widget_set_name (label5, "label5");
  gtk_widget_show (label5);
  gtk_table_attach (GTK_TABLE (table1), label5, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label5), 0, 0.5);

  label6 = gtk_label_new (_("Organizer"));
  gtk_widget_set_name (label6, "label6");
  gtk_widget_show (label6);
  gtk_table_attach (GTK_TABLE (table1), label6, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label6), 0, 0.5);

  label3 = gtk_label_new (_("Images"));
  gtk_widget_set_name (label3, "label3");
  gtk_widget_show (label3);
  gtk_table_attach (GTK_TABLE (table1), label3, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label3), 0, 0.5);

  checkMusic = gtk_check_button_new_with_mnemonic (_("Sync"));
  gtk_widget_set_name (checkMusic, "checkMusic");
  gtk_widget_show (checkMusic);
  gtk_table_attach (GTK_TABLE (table1), checkMusic, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkPlaylists = gtk_check_button_new_with_mnemonic (_("Sync"));
  gtk_widget_set_name (checkPlaylists, "checkPlaylists");
  gtk_widget_show (checkPlaylists);
  gtk_table_attach (GTK_TABLE (table1), checkPlaylists, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkImages = gtk_check_button_new_with_mnemonic (_("Sync"));
  gtk_widget_set_name (checkImages, "checkImages");
  gtk_widget_show (checkImages);
  gtk_table_attach (GTK_TABLE (table1), checkImages, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkVideos = gtk_check_button_new_with_mnemonic (_("Sync"));
  gtk_widget_set_name (checkVideos, "checkVideos");
  gtk_widget_show (checkVideos);
  gtk_table_attach (GTK_TABLE (table1), checkVideos, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkZencasts = gtk_check_button_new_with_mnemonic (_("Sync"));
  gtk_widget_set_name (checkZencasts, "checkZencasts");
  gtk_widget_show (checkZencasts);
  gtk_table_attach (GTK_TABLE (table1), checkZencasts, 2, 3, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  checkOrganizer = gtk_check_button_new_with_mnemonic (_("Sync"));
  gtk_widget_set_name (checkOrganizer, "checkOrganizer");
  gtk_widget_show (checkOrganizer);
  gtk_table_attach (GTK_TABLE (table1), checkOrganizer, 2, 3, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  dialog_action_area1 = GTK_DIALOG (dialogSetup)->action_area;
  gtk_widget_set_name (dialog_action_area1, "dialog_action_area1");
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  cancelbutton1 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_set_name (cancelbutton1, "cancelbutton1");
  gtk_widget_show (cancelbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialogSetup), cancelbutton1, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton1, GTK_CAN_DEFAULT);

  okbutton1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_set_name (okbutton1, "okbutton1");
  gtk_widget_show (okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialogSetup), okbutton1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton1, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialogSetup, dialogSetup, "dialogSetup");
  GLADE_HOOKUP_OBJECT_NO_REF (dialogSetup, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (dialogSetup, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (dialogSetup, label7, "label7");
  GLADE_HOOKUP_OBJECT (dialogSetup, table1, "table1");
  GLADE_HOOKUP_OBJECT (dialogSetup, fileMusic, "fileMusic");
  GLADE_HOOKUP_OBJECT (dialogSetup, filePlaylists, "filePlaylists");
  GLADE_HOOKUP_OBJECT (dialogSetup, fileImages, "fileImages");
  GLADE_HOOKUP_OBJECT (dialogSetup, fileVideo, "fileVideo");
  GLADE_HOOKUP_OBJECT (dialogSetup, fileZencast, "fileZencast");
  GLADE_HOOKUP_OBJECT (dialogSetup, fileOrganizer, "fileOrganizer");
  GLADE_HOOKUP_OBJECT (dialogSetup, label1, "label1");
  GLADE_HOOKUP_OBJECT (dialogSetup, label2, "label2");
  GLADE_HOOKUP_OBJECT (dialogSetup, label4, "label4");
  GLADE_HOOKUP_OBJECT (dialogSetup, label5, "label5");
  GLADE_HOOKUP_OBJECT (dialogSetup, label6, "label6");
  GLADE_HOOKUP_OBJECT (dialogSetup, label3, "label3");
  GLADE_HOOKUP_OBJECT (dialogSetup, checkMusic, "checkMusic");
  GLADE_HOOKUP_OBJECT (dialogSetup, checkPlaylists, "checkPlaylists");
  GLADE_HOOKUP_OBJECT (dialogSetup, checkImages, "checkImages");
  GLADE_HOOKUP_OBJECT (dialogSetup, checkVideos, "checkVideos");
  GLADE_HOOKUP_OBJECT (dialogSetup, checkZencasts, "checkZencasts");
  GLADE_HOOKUP_OBJECT (dialogSetup, checkOrganizer, "checkOrganizer");
  GLADE_HOOKUP_OBJECT_NO_REF (dialogSetup, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (dialogSetup, cancelbutton1, "cancelbutton1");
  GLADE_HOOKUP_OBJECT (dialogSetup, okbutton1, "okbutton1");

  return dialogSetup;
}

GtkWidget*
create_dialogProgress (void)
{
  GtkWidget *dialogProgress;
  GtkWidget *dialog_vbox2;
  GtkWidget *progressbar;
  GtkWidget *dialog_action_area2;
  GtkWidget *buttonCloseProgress;

  dialogProgress = gtk_dialog_new ();
  gtk_widget_set_name (dialogProgress, "dialogProgress");
  gtk_window_set_title (GTK_WINDOW (dialogProgress), _("Updating Device"));
  gtk_window_set_position (GTK_WINDOW (dialogProgress), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (dialogProgress), TRUE);
  gtk_window_set_default_size (GTK_WINDOW (dialogProgress), 200, -1);

  dialog_vbox2 = GTK_DIALOG (dialogProgress)->vbox;
  gtk_widget_set_name (dialog_vbox2, "dialog_vbox2");
  gtk_widget_show (dialog_vbox2);

  progressbar = gtk_progress_bar_new ();
  gtk_widget_set_name (progressbar, "progressbar");
  gtk_widget_show (progressbar);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), progressbar, FALSE, FALSE, 0);
  gtk_progress_bar_set_ellipsize (GTK_PROGRESS_BAR (progressbar), PANGO_ELLIPSIZE_START);

  dialog_action_area2 = GTK_DIALOG (dialogProgress)->action_area;
  gtk_widget_set_name (dialog_action_area2, "dialog_action_area2");
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  buttonCloseProgress = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_set_name (buttonCloseProgress, "buttonCloseProgress");
  gtk_widget_show (buttonCloseProgress);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialogProgress), buttonCloseProgress, GTK_RESPONSE_CLOSE);
  gtk_widget_set_sensitive (buttonCloseProgress, FALSE);
  GTK_WIDGET_SET_FLAGS (buttonCloseProgress, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) buttonCloseProgress, "clicked",
                    G_CALLBACK (on_buttonCloseProgress_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialogProgress, dialogProgress, "dialogProgress");
  GLADE_HOOKUP_OBJECT_NO_REF (dialogProgress, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (dialogProgress, progressbar, "progressbar");
  GLADE_HOOKUP_OBJECT_NO_REF (dialogProgress, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (dialogProgress, buttonCloseProgress, "buttonCloseProgress");

  return dialogProgress;
}

